config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,        except:   [:new, :create] do
    resource :relationships, only:   [:create, :destroy]
  end
  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'sort' => 'posts#sort'
  resources :posts do
    resources :comments,      only:   [:create, :destroy]
    resource  :favorits,      only:   [:create, :destroy]
  end
  resources :tags,          only:   [:create]
  get 'search' => 'searchs#search'
  resources :rooms,         only:   [:create, :show]
  resources :messages,      only:   [:create]
  get 'followeds/:id' => 'users#followeds', as: 'followeds'
  get 'followers/:id' => 'users#followers', as: 'followers'
  resources :notifications, only:   [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit.rb
class Favorit < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy

  validates :text, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :room, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :tag_relationships
  has_many :tags, through: :tag_relationships

  validates :introduction, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorits.where(user_id: user.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      tag_relationshipss_records = TagRelationship.where(post_id: self.id)
      tag_relationshipss_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(name: tag).first_or_create
      self.tags << inspected_tag
    end
  end

  is_impressionable counter_cache: true

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'like'
      return all.includes(:favorits).sort {|a,b| b.favorits.count <=> a.favorits.count}
    when 'dislike'
      return all.includes(:favorits).sort {|a,b| a.favorits.count <=> b.favorits.count}
    when 'view'
      return all.order(impressions_count: :DESC)
    when 'not_view'
      return all.order(impressions_count: :ASC)
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  def take_colors(image_url, quantity: 10, threshold: 1)
    return [] if image_url.nil?
    image = MiniMagick::Image.open(image_url)
    result = image.run_command('convert', image_url, '-format', '%c', '-colors', quantity, '-depth', 8, 'histogram:info')
  
    frequencies = result.scan(/([0-9]+)\:/).flatten.map { |m| m.to_f }
    hex_values = result.scan(/(\#[0-9ABCDEF]{6})/).flatten
  
    total_frequencies = colors.reduce(0.0) { |sum, (_, freq)| sum += freq }.to_f
    colors.
      map { |(hex, freq)| [hex, (freq * 100 / total_frequencies).to_i] }.
      reject { |(hex, freq)| freq < threshold }.
      sort_by { |(hex, freq)| freq }.reverse
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_relationships
  has_many :posts, through: :tag_relationships

  def self.search(keyword)
    @tags = Tag.where("name LIKE ?", "%#{keyword}%")
  end

end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true

  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(keyword)
    @users = User.where("name LIKE ?", "%#{keyword}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
    if user_signed_in?
      @current_user_entrie = Entry.where(user_id: current_user.id)
      @user_entrie = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @current_user_entrie.each do |cu|
          @user_entrie.each do |u|
            if cu.room_id == u.room_id then
              @room = true
              @room_id = cu.room_id
            end
          end
        end
        if @room
        else
          @room_new = Room.new
          @entrie = Entry.new
        end
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user)
  end

  def followeds
    @user = User.find(params[:id])
    @followeds = @user.follower_user
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.following_user
  end

  private

  def user_params
    params.require(:user).permit(:image, :name, :introduction)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorits_helper.rb
module FavoritsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <%= form_with model:@user, local:true do |f| %>
        <div class="py-2">
          プロフィール画像: <%= f.attachment_field :image %>
        </div>
        <div class="py-2">
          名前: <%= f.text_field :name, value: @user.name %>
        </div>
        <div class="py-2">
          自己紹介文: <%= f.text_area :introduction, value: @user.introduction, size: "30x8" %>
        </div>
        <div class="py-2">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followeds.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>アイコン</th>
            <th>名前</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @followeds.each do |followed| %>
            <tr>
              <td>
                <%= link_to user_path(followed) do %>
                  <%= attachment_image_tag followed, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
                <% end %>
                </td>
              <td><%= followed.name %></td>
              <td>
                <% if user_signed_in? %>
                  <% unless current_user == followed %>
                    <% if current_user.following?(followed) %>
                      <%= link_to 'フォロー外す', user_relationships_path(followed), method: :delete, class: "btn btn-danger btn-sm" %>
                    <% else %>
                      <%= link_to 'フォロー', user_relationships_path(followed), method: :post, class: "btn btn-primary btn-sm" %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>アイコン</th>
            <th>名前</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @followers.each do |follower| %>
            <tr>
              <td>
                <%= link_to user_path(follower) do %>
                  <%= attachment_image_tag follower, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
                <% end %>
                </td>
              <td><%= follower.name %></td>
              <td>
                <% if user_signed_in? %>
                  <% unless current_user == follower %>
                    <% if current_user.following?(follower) %>
                      <%= link_to 'フォロー外す', user_relationships_path(follower), method: :delete, class: "btn btn-danger btn-sm" %>
                    <% else %>
                      <%= link_to 'フォロー', user_relationships_path(follower), method: :post, class: "btn btn-primary btn-sm" %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>アイコン</th>
            <th>名前</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
                <% end %>
                </td>
              <td><%= user.name %></td>
              <td>
                <% if user_signed_in? %>
                  <% unless current_user == user %>
                    <% if current_user.following?(user) %>
                      <%= link_to 'フォロー外す', user_relationships_path(user), method: :delete, class: "btn btn-danger btn-sm" %>
                    <% else %>
                      <%= link_to 'フォロー', user_relationships_path(user), method: :post, class: "btn btn-primary btn-sm" %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <div class="py-2">
        プロフィール画像: <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
      </div>
      <div class="py-2">
        名前: <%= @user.name %>
      </div>
      <div class="py-2">
        自己紹介文: <%= @user.introduction %>
      </div>
      <div class="py-2">
        フォロー：
        <%= link_to followeds_path, class:"no-underline" do %>
          <%= @user.follower_user.count %>
        <% end %>
      </div>
      <div class="py-2">
        フォロワー：
        <%= link_to followers_path, class:"no-underline" do %>
          <%= @user.following_user.count %>
        <% end %>
      </div>
      <div class="py-2">
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <%= link_to "プロフィール編集", edit_user_path, class: "btn btn-success btn-sm" %>
          <% elsif current_user.following?(@user) %>
            <%= link_to 'フォロー外す', user_relationships_path(@user), method: :delete, class: "btn btn-danger btn-sm" %>
          <% else %>
            <%= link_to 'フォロー', user_relationships_path(@user), method: :post, class: "btn btn-primary btn-sm" %>
          <% end %>
        <% end %>
      </div>
      <div class="py-2">
        <% if user_signed_in? %>
          <% unless @user.id == current_user.id %>
            <% if (current_user.following? @user) && (@user.following? current_user) %>
              <% if @room == true %>
                <%= link_to "チャットへ", room_path(@room_id), class: "btn btn-primary btn-sm" %>
              <% else %>
                <%= form_with model: @room_new do |f| %>
                  <%= fields_for @entrie do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id %>
                  <% end %>
                  <%= f.submit "チャットを始める", class:"btn btn-primary btn-sm user-show-chat" %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <% if user_signed_in? && current_user == @user %>
        <%= link_to new_post_path, class:"no-underline" do %>
          <div class="fas fa-plus plus-botton pr-2 btn btn-primary btn-sm"> 新規投稿</div>
        <% end %>
        <%= link_to notifications_path, class:"no-underline" do %>
          <div class="fas fa-exclamation pl-2 btn btn-warning btn-sm"> 通知一覧</div>
        <% end %>
      <% end %>
      <%= render "posts/index", posts: @posts %>
    </div>
  </div>
</div>