config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,        except:   [:new, :create] do
    resource :relationships, only:   [:create, :destroy]
  end
  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'sort' => 'posts#sort'
  resources :posts do
    resources :comments,      only:   [:create, :destroy]
    resource  :favorits,      only:   [:create, :destroy]
  end
  resources :tags,          only:   [:create]
  get 'search' => 'searchs#search'
  resources :rooms,         only:   [:create, :show]
  resources :messages,      only:   [:create]
  get 'followeds/:id' => 'users#followeds', as: 'followeds'
  get 'followers/:id' => 'users#followers', as: 'followers'
  resources :notifications, only:   [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit.rb
class Favorit < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy

  validates :text, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :room, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :tag_relationships
  has_many :tags, through: :tag_relationships

  validates :introduction, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorits.where(user_id: user.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      tag_relationshipss_records = TagRelationship.where(post_id: self.id)
      tag_relationshipss_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(name: tag).first_or_create
      self.tags << inspected_tag
    end
  end

  is_impressionable counter_cache: true

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'like'
      return all.includes(:favorits).sort {|a,b| b.favorits.count <=> a.favorits.count}
    when 'dislike'
      return all.includes(:favorits).sort {|a,b| a.favorits.count <=> b.favorits.count}
    when 'view'
      return all.order(impressions_count: :DESC)
    when 'not_view'
      return all.order(impressions_count: :ASC)
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  def take_colors(image_url, quantity: 10, threshold: 1)
    return [] if image_url.nil?
    image = MiniMagick::Image.open(image_url)
    result = image.run_command('convert', image_url, '-format', '%c', '-colors', quantity, '-depth', 8, 'histogram:info')
  
    frequencies = result.scan(/([0-9]+)\:/).flatten.map { |m| m.to_f }
    hex_values = result.scan(/(\#[0-9ABCDEF]{6})/).flatten
  
    total_frequencies = colors.reduce(0.0) { |sum, (_, freq)| sum += freq }.to_f
    colors.
      map { |(hex, freq)| [hex, (freq * 100 / total_frequencies).to_i] }.
      reject { |(hex, freq)| freq < threshold }.
      sort_by { |(hex, freq)| freq }.reverse
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_relationships
  has_many :posts, through: :tag_relationships

  def self.search(keyword)
    @tags = Tag.where("name LIKE ?", "%#{keyword}%")
  end

end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true

  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(keyword)
    @users = User.where("name LIKE ?", "%#{keyword}%")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  impressionist actions: [:index, :show]

  def index
    @posts = Post.page(params[:page]).reverse_order
  end

  def new
    @post =  Post.new
  end

  def create
    @post = Post.new(post_params)
    tag_list = params[:post][:names].split(",")
    @post.user_id = current_user.id
    if @post.save
      @post.tags_save(tag_list)
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @user = @post.user
    impressionist(@post, nil, unique: [:impressionable_id, :ip_address])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:names].split(",")
    @post.update(post_params)
    @post.tags_save(tag_list)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def sort
    selection = params[:keyword]
    @posts = Kaminari.paginate_array(Post.sort(selection)).page(params[:page])
    @value = params[:keyword]
  end

  private

  def post_params
    params.require(:post).permit(:image, :introduction)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorits_helper.rb
module FavoritsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_comment.html.erb
<div class="py-1">
  <%= post_one.comments.count %> 件のコメント
</div>
<% post_one.comments.each do |post_comment| %>
  <div class="py-1">
    <%= post_comment.user.name %>
  </div>
  <div class="py-1">
    <%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_comment_path(post_one, post_comment), method: :delete, remote: true , class: "btn btn-danger btn-sm" %>
    <% end %>
  </div>
<% end %>
<% if user_signed_in? %>
  <%= form_with(model:[post_one, comment_one]) do |f| %>
    <div class="py-1">
      <%= f.text_field :comment, rows:'5',placeholder: "コメントをここに" %>
    </div>
    <div class="py-1">
      <%= f.submit "送信する" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_favorit.html.erb
<% if user_signed_in? %>
  <% if post_one.favorited_by?(current_user) %>
    <div class="py-1">
      <%= link_to post_favorits_path(post_one), method: :delete, remote: true, class:"no-underline" do %>
        ♥<%= post_one.favorits.count %> いいね
      <% end %>
    </div>
    <% else %>
    <div class="py-1">
      <%= link_to post_favorits_path(post_one), method: :post, remote: true, class:"no-underline" do %>
        ♡<%= post_one.favorits.count %> いいね
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="py-1">
    <%= post_one.favorits.count %>いいね
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= render 'layouts/error_messages', model: new_post %>
<div>
  <%= form_with model: new_post, local: true do |f| %>
    <div class="py-2">
      投稿画像: <%= f.attachment_field :image %>
    </div>
    <div class="py-2">
      投稿文: <%= f.text_area :introduction, value: new_post.introduction, size: "30x8" %>
    </div>
    <div class="py-2">
      タグ: <%= f.text_field :names, placeholder: ",で区切ってください", size: "40x10" %>
    </div>
    <div class="py-2">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/_index.html.erb
<div class="index-flex">
  <% posts.each do |post_one| %>
    <div class="post-background-color border p-2 m-1">
      <div class="py-1">
        <%= link_to user_path(post_one.user), class:"no-underline" do %>
          <%= attachment_image_tag post_one.user, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
        <% end %>
        <%= post_one.user.name %>
      </div>
      <div class="py-1 img_wrap">
        <%= link_to post_path(post_one) do %>
          <%= attachment_image_tag post_one, :image, :fill, 300, 300, fallback: "no_image.jpg", class: "img_pointer" %>
        <% end %>
      </div>
      <div class="py-1 break-word-index">
       <%= post_one.introduction.truncate(18) %>
      </div>
      <div class="py-1">
        <% post_one.tags.each do |tag| %>
          #<%= tag.name %>
        <% end %>
      </div>
      <div class="py-1">
        <%= post_one.comments.count %>コメント
        <div id="favorit_buttons_<%= post_one.id %>">
          <%= render 'posts/favorit', post_one: post_one %>
        </div>
      </div>
      <div class="py-1">
        <%= post_one.impressionist_count %> 閲覧
      </div>
    </div>
  <% end %>
</div>
<%= paginate posts %>

app/views/posts/edit.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <%= render 'form', new_post: @post %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <div class="py-2">
        <%= form_with model: @post, url: sort_path, method: :get, local: true do |f| %>
          <%= f.select :keyword, [['新しい投稿順', 'new'], ['古い投稿順', 'old'], ['いいね数が多い順', 'like'], ['いいね数が少ない順', 'dislike'], ['閲覧数が多い順', 'view'], ['閲覧数が少ない順', 'not_view']]%>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <%= render 'index', posts: @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <%= render 'form', new_post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div clsss="row">
    <div class="col-12 my-2">
      <div class="post-background-color border p-2 m-1">
        <div class="py-1">
          <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :image, :fill, 100, 100, fallback: "no_image.jpg", class: "img_icon" %>
          <% end %>
          <%= @user.name %>
        </div>
        <div class="py-1">
          <%= attachment_image_tag @post, :image, :fill, 300, 300, fallback: "no_image.jpg", class: "img_pointer" %>
        </div>
        <div class="py-1 break-word-show mx-auto">
          <%= @post.introduction %>
        </div>
        <div class="py-1">
          <% @post.tags.each do |tag| %>
            #<%= tag.name %>
          <% end %>
        </div>
        <div class="py-1">
          <% if @post.user == current_user %>
            <%= link_to "編集する", edit_post_path(@post), class: "btn btn-success btn-sm" %>
            <%= link_to "投稿削除", post_path(@post), method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
        <div id="favorit_buttons_<%= @post.id %>">
          <%= render 'posts/favorit', post_one: @post %>
        </div>
        <div id="comment_index">
          <%= render 'posts/comment', post_one: @post, comment_one: @comment %>
        </div>
        <div class="py-1">
          <%= @post.impressionist_count %> 閲覧
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/sort.html.erb
<div class="container">
  <div clsss="row my-3">
    <div class="col-12 my-2">
      <div class="py-2">
        <%= form_with model: @post, url: sort_path, method: :get do |f| %>
          <%= f.select :keyword, [['新しい投稿順', 'new'], ['古い投稿順', 'old'], ['いいね数が多い順', 'like'], ['いいね数が少ない順', 'dislike'], ['閲覧数が多い順', 'view'], ['閲覧数が少ない順', 'not_view']] %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <div id="sort_result">
        <%= render 'index', posts: @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/sort.js.erb
$('#sort_result').html("<%= j(render 'index', posts: @posts) %>")