config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,        except:   [:new, :create] do
    resource :relationships, only:   [:create, :destroy]
  end
  root to: 'homes#top'
  get 'about' => 'homes#about'
  get 'sort' => 'posts#sort'
  resources :posts do
    resources :comments,      only:   [:create, :destroy]
    resource  :favorits,      only:   [:create, :destroy]
  end
  resources :tags,          only:   [:create]
  get 'search' => 'searchs#search'
  resources :rooms,         only:   [:create, :show]
  resources :messages,      only:   [:create]
  get 'followeds/:id' => 'users#followeds', as: 'followeds'
  get 'followers/:id' => 'users#followers', as: 'followers'
  resources :notifications, only:   [:index, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorit.rb
class Favorit < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy

  validates :text, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  belongs_to :room, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  attachment :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :tag_relationships
  has_many :tags, through: :tag_relationships

  validates :introduction, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorits.where(user_id: user.id).exists?
  end

  def tags_save(tag_list)
    if self.tags != nil
      tag_relationshipss_records = TagRelationship.where(post_id: self.id)
      tag_relationshipss_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(name: tag).first_or_create
      self.tags << inspected_tag
    end
  end

  is_impressionable counter_cache: true

  def self.sort(selection)
    case selection
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'like'
      return all.includes(:favorits).sort {|a,b| b.favorits.count <=> a.favorits.count}
    when 'dislike'
      return all.includes(:favorits).sort {|a,b| a.favorits.count <=> b.favorits.count}
    when 'view'
      return all.order(impressions_count: :DESC)
    when 'not_view'
      return all.order(impressions_count: :ASC)
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/models/search.rb
class Search < ApplicationRecord
  def take_colors(image_url, quantity: 10, threshold: 1)
    return [] if image_url.nil?
    image = MiniMagick::Image.open(image_url)
    result = image.run_command('convert', image_url, '-format', '%c', '-colors', quantity, '-depth', 8, 'histogram:info')
  
    frequencies = result.scan(/([0-9]+)\:/).flatten.map { |m| m.to_f }
    hex_values = result.scan(/(\#[0-9ABCDEF]{6})/).flatten
  
    total_frequencies = colors.reduce(0.0) { |sum, (_, freq)| sum += freq }.to_f
    colors.
      map { |(hex, freq)| [hex, (freq * 100 / total_frequencies).to_i] }.
      reject { |(hex, freq)| freq < threshold }.
      sort_by { |(hex, freq)| freq }.reverse
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :tag_relationships
  has_many :posts, through: :tag_relationships

  def self.search(keyword)
    @tags = Tag.where("name LIKE ?", "%#{keyword}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorits, dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :name, presence: true

  def follow(user_id)
    follower.create!(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.search(keyword)
    @users = User.where("name LIKE ?", "%#{keyword}%")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorits_helper.rb
module FavoritsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<div class="py-2">
  <% if model.errors.any? %>
    <div class="alert alert-warning">
      <%= model.errors.count %>個のエラーが確認されました<br>
      <% model.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="background">
  <div class="y-1">
    <%= image_tag 'logo_origin.png', :size => '200x200' %>
  </div>
  <div class="y-1">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, value: keyword %>
      <%= f.select :range, options_for_select([['ユーザー'], ['タグ']]) %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
  <div class="y-1">
    <% if user_signed_in? %>
      <li>
        <%= link_to "マイページ", user_path(current_user),class: 'fas fa-user nav-link text-light' %>
      </li>
      <li>
        <%= link_to "ユーザー一覧", users_path,class: 'fas fa-users nav-link text-light' %>
      </li>
      <li>
        <%= link_to "投稿一覧", root_path,class: 'fas fa-paste nav-link text-light' %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-light' %>
      </li>
      <li>
        <%= link_to "ユーザー一覧", users_path,class: 'fas fa-users nav-link text-light' %>
      </li>
      <li>
        <%= link_to "投稿一覧", root_path,class: 'fas fa-paste nav-link text-light' %>
      </li>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coordinator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=devise-width, initial-scale=1.0, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to root_path, class:"no-underline" do %>
          <div class="navbar-brand h1 my-auto">COORDINATOR</div>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <% if user_signed_in? %>
    　      <ul class="navbar-nav mr-auto">
    　        <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user),class: 'fas fa-user nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "ユーザー一覧", users_path,class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path,class: 'fas fa-paste nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>
    　      </ul>
          <% else %>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path,class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "サイト概要", about_path,class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path,class: 'fas fa-paste nav-link text-light' %>
              </li>
            </ul>
          <% end %>
          <%= form_with url: search_path, method: :get, local: true, class:"form-inline my-2 my-lg-0" do |f| %>
            <%= f.select :range, options_for_select([['ユーザー'], ['タグ']]) %>
            <%= f.text_field :keyword, value: @keyword, class: "form-control mx-sm-2" %>
            <%= f.submit "Search", class:"btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>